name: Release on Github

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with gradlew
        run: ./gradlew buildAll
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bodyFile: "CHANGELOG.md"
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: "modules/bukkit/build/libs/*.jar,modules/fabric_1.20.1/build/libs/*.jar"
            


